# Generated by Django 5.0.6 on 2024-05-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.CharField()),
                ('address', models.CharField()),
                ('phone', models.CharField()),
            ],
        ),
    ]
